name: Client CI

on:
  push:
    branches: [ main ]
    paths:
      - client/**
  pull_request:
    branches: [ main ]
    paths:
      - client/**

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - working-directory: client
        run: |
          npm ci
          npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - working-directory: client
        run: |
          npm ci
          npm run lint
